### ISSUE TITLE
Branch 2.0 running on Windows 10

### ISSUE THREAD

**Issue by RainerAtSpirit** [tomitrescak/luis#2]
Just as a heads up to the upcoming 2.0 release.
I got the 2.0 branch working on a Mac, but when trying to run on Windows 10 I've noticed an issue with setting environment variables.

e.g.

https://github.com/tomitrescak/luis/blob/c5b5702c4b9889261a49f96379b3d553c8c91e27/package.json#L9

will fail on Windows. Instead you would have to write something like
```set TS_NODE_FAST=true&& mocha```

These variables will be set in some server scripts as well, so I'm not sure what would be the best way to make them work across environments.

As a quick hack I updated those instances manually, but the system still fails with a cryptic message when trying to update a given snapshot from the client UI.
```
set TS_NODE_FAST=true&& set UPDATE_SNAPSHOTS=true&& ./node_modules/.bin/mocha --require ./mocha.js --ui snapshots undefined 'src/**/*.test.ts*' --compilers ts:ts-node/register --grep "Foo"
'.' is not recognized as an internal or external command,
operable program or batch file.
```
All in all great improvements since the 1.x release.
Really looking forward for version 2.0 to be released :)

**Comment by tomitrescak** [comment]
Wow, you got balls my friend ! :)) Kudos on making it work without documentation !!!!!!!

Yeah, the 2.0 is MUCH more stable and alsmost does not need reloads. It's runs only updated tests and much more. 

I am not sure how to deal with environment variables on Windows though ;(

**Comment by RainerAtSpirit** [comment]
:), I'm in the need for a super fast, easy to use, reliable UI component test runner. Waiting for official release though before tackling environment issues on Windows 10.

**Comment by tomitrescak** [comment]
Well, you are in a good spot. will happen soon. working on docs and stabilising the package now. It's in beta.

**Comment by RainerAtSpirit** [comment]
Excellent. I'll review docs tomorrow. Let me know if I can help on something.
