### ISSUE TITLE
Branch 2.0 yarn.lock

### ISSUE THREAD

**Issue by RainerAtSpirit** [tomitrescak/luis#3]
When trying to install via yarn, I'm getting the following;
```
[2/4] Fetching packages...
error An unexpected error occurred: "http://localhost:4873/body-parser/-/body-parser-1.18.1.tgz: connect ECONNREFUSED 127.0.0.1:4873".
```

Looks like you're running a local npm registry?
https://github.com/tomitrescak/luis/blob/3716b4c390ac51b4d1f7db521f49812bd9e09e1d/yarn.lock#L305

**Comment by tomitrescak** [comment]
@RainerAtSpirit I will release the official version soon, up until now it was work in progress. Will post back once that's done!

**Comment by RainerAtSpirit** [comment]
waiting for official release.
